encoding: utf-8
lang: ja
timezone: Asia/Tokyo

plugins: ["jekyll-remote-theme", "jekyll-sitemap", "jekyll-feed"]
remote_theme: ress997/jekyll-wolke

url: https://glyzinie.github.io
title: Glyzinie
description: Wistaria
copyright: 2023 Glyzinie
